### PR TITLE
Provide ability to allow user to use config option to disable cron op…

### PR DESCRIPTION
**Pull request by Wu-Jing**
…tion: Minutes, Years, etc

Just like https://github.com/angular-cron-jobs/angular-cron-jobs
See `###Options`

### CODE REVIEW

**Comment by Wu-Jing** [comment]
@rvalenciano please let me know if you have any questions. You can see the link mentioned above and search '###Options', or take a look at the readme file in this PR.

**Comment by rvalenciano** [comment]
@yp2 could you update your fork and the npm version?

**Comment by Wu-Jing** [comment]
Thanks guys! @rvalenciano @yp2

**Comment by yp2** [comment]
Hi guys! 

@Wu-Jing I think that we should not use labels in options. Labels are used on templates. Better solution is to add a field to CronJobsSelectOption with type of this filed, which then will be used in options. Also there are no test for this if branch. 
@Wu-Jing could you make next pull request to my repository - review will be easier.

**Comment by Wu-Jing** [comment]
@yp2  Thanks for the feedback. could you elaborate more on adding this to CronJobsSelectOption? As far as I understand, there is no external way to modify the array of CronJobsSelectOption (frequencies).  And similarly how the js version of this implemented this feature. 
Thanks.

**Pull request merged**
